### ISSUE TITLE
worker_1  | Connecting to redis last line in output, Vote app is not working

### ISSUE THREAD

**Issue by zeenmc** [dockersamples/example-voting-app#195]
Hello Team,

I tried with docker-compose to create swarm, on Ubuntu 20.04, last which I got is output from below.
I am not sure how to resolve this issue.

Please assist.
FYI This is my first issue opened, I am not sure am I doing anything correct  :)

zeenmc@vista:~$ docker --version
Docker version 19.03.8, build afacb8b7f0
zeenmc@vista:~$ docker-compose --version
docker-compose version 1.27.3, build 4092ae5d
zeenmc@vista:~$ 

Kindly see output from below.

Thank you in advance.

db        | PostgreSQL init process complete; ready for start up.
db        | 
db        | LOG:  database system was shut down at 2021-01-25 02:58:58 UTC
db        | LOG:  MultiXact member wraparound protections are now enabled
db        | LOG:  database system is ready to accept connections
db        | LOG:  autovacuum launcher started
result_1  | Connected to db
db        | ERROR:  relation "votes" does not exist at character 38
db        | STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
result_1  | Error performing query: error: relation "votes" does not exist
worker_1  | Connected to db
worker_1  | Found redis at 172.20.0.3
worker_1  | Connecting to redis

**Comment by pfelwor** [comment]
Facing the same issue deploying on Openshift 4.7

**Comment by yashwanthkota** [comment]
This issue is occurs even if I run the following:
docker-compose -f docker-compose-simple.yml up

Sample log:
result_1  | [nodemon] starting `node server.js`
vote_1    |  * Serving Flask app 'app' (lazy loading)
vote_1    |  * Environment: production
vote_1    |    WARNING: This is a development server. Do not use it in a production deployment.
vote_1    |    Use a production WSGI server instead.
vote_1    |  * Debug mode: on
vote_1    |  * Running on all addresses.
vote_1    |    WARNING: This is a development server. Do not use it in a production deployment.
vote_1    |  * Running on http://172.18.0.5:80/ (Press CTRL+C to quit)
vote_1    |  * Restarting with stat
vote_1    |  * Debugger is active!
vote_1    |  * Debugger PIN: 129-446-285
result_1  | Sun, 20 Mar 2022 03:51:30 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at server.js:73:9
result_1  | Sun, 20 Mar 2022 03:51:30 GMT body-parser deprecated undefined extended: provide extended option at ../node_modules/body-parser/index.js:105:29
result_1  | App running on port 80
result_1  | Connected to db
worker_1  | Connected to db
worker_1  | Found redis at 172.18.0.3
worker_1  | Connecting to redis

**Comment by zeenmc** [comment]
> This issue is occurs even if I run the following: docker-compose -f docker-compose-simple.yml up
> 
> Sample log: result_1 | [nodemon] starting `node server.js` vote_1 | * Serving Flask app 'app' (lazy loading) vote_1 | * Environment: production vote_1 | WARNING: This is a development server. Do not use it in a production deployment. vote_1 | Use a production WSGI server instead. vote_1 | * Debug mode: on vote_1 | * Running on all addresses. vote_1 | WARNING: This is a development server. Do not use it in a production deployment. vote_1 | * Running on http://172.18.0.5:80/ (Press CTRL+C to quit) vote_1 | * Restarting with stat vote_1 | * Debugger is active! vote_1 | * Debugger PIN: 129-446-285 result_1 | Sun, 20 Mar 2022 03:51:30 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at server.js:73:9 result_1 | Sun, 20 Mar 2022 03:51:30 GMT body-parser deprecated undefined extended: provide extended option at ../node_modules/body-parser/index.js:105:29 result_1 | App running on port 80 result_1 | Connected to db worker_1 | Connected to db worker_1 | Found redis at 172.18.0.3 worker_1 | Connecting to redis

Hello @yashwanthkota, image is working fine, just you need to use -d or --detached option

docker-compose up -d

and of course to wait for services to be ready.

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
