### ISSUE TITLE
performing replicas for each db, redis and worker.

### ISSUE THREAD

**Issue by cantprogram01** [dockersamples/example-voting-app#235]
all is good now deployments are working,
but i want to know how do we perform scale up
for the db, redis and workers. it seems that when i do 2 replicas for each pods it's getting confused and doesn't know where to connect itself.

**Comment by BretFisher** [comment]
Depending on the design of an application, you can't add replicas without additional considerations, which are very app-specific.

vote: can scale to many replicas
worker: can scale to many replicas
result: can't scale beyond 1 replica without LB stick sessions because it uses socket.io
db: you'd need a specific postgres replication and failover solution
redis: you'd need a specific redis replication and failover solution
