### ISSUE TITLE
Second redis service is redundant

### ISSUE THREAD

**Issue by zavermax** [dockersamples/example-voting-app#73]
There are two redis services and one worker service. Worker service would start, resolve redis host name to an ip and use this ip until stopped. Second redis service is never going to be talked to.

**Comment by alexsandro-xpt** [comment]
I saw something like this at `docker-stack.yml` but I have some question about Redis IP used at Worker Services to connect to Redis.

There are twice Redis instance, I thing, Worker never discover a second Redis instance. May be, Redis shoud be configured as node of Redis if is possible.

Another thing is about Redis host name, the Vote App and Worker Services connect at redis host name. If at cluster have twice Redis instance, Vote every time connect to what Redis instance?

Some times when I vote, the vote is not computed, I guess, my vote was at another Redis which is not connected by Worker Services.

What you think about that @zavermax ?

**Comment by gesellix** [comment]
If I understand the .NET worker correctly, it tries to reconnect on failure. So a changed ip address might be compensated. The Java worker doesn't seem to be resilient on connection errors, yet.

The fact that a worker can only connect to a single Redis instance indeed arises problems when votes go to the "other" instance. The worker just won't see any votes. I see several options here:

1. reduce the Redis replicas to a single instance
2. implement a Redis cluster, so that data will be synced between all replicas
3. enforce reconnects on the worker side, so that each Redis instance will be read over time. This wouldn't be the most elegant solution, but it has certain adavantages (no-cluster Redis setup, built-in resiliency)

**Comment by alexsandro-xpt** [comment]
At my demo enviroment I reduce the Redis replicas to a single instance and all work fine.

But, I guess the better solution is implement a Redis Cluster like you told us.

Another bad thing I see at .NET worker is that `while(true)` https://github.com/docker/example-voting-app/blob/master/worker/src/Worker/Program.cs#L29 it's cost lot of CPU unnecessary. May be implement something better.

I think change Redis for an RabbitMQ.

**Comment by ManoMarks** [comment]
Fixed
